# Generated by Django 6.0.5 on 2026-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('client', 'I need a service'), ('provider', 'I offer a service')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
