# Generated by Django 6.0.5 on 2026-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
